install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y cabal
  - choco install -y ghc --version 8.2.2
  - refreshenv
  # See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491
  # NB: Do this after refreshenv, otherwise it will be clobbered!
  - set PATH=%APPDATA%\cabal\bin;C:\Program Files\Git\mingw64\bin;%PATH%
  - cabal --version
  - cabal update

cache:
  - dist-newstyle

build_script:
  - cabal new-configure --enable-tests
  - cabal new-build lib:Cabal
  - cabal new-test Cabal
  - cabal new-build exe:cabal
  - cabal new-run cabal-tests -- -j3 --with-cabal=..\cabal-install\dist-newstyle\build\x86_64-win32\cabal-install-2.3.0.0\build\cabal\cabal.exe
  - cabal new-test cabal-install
