install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y cabal
  - choco install -y ghc --version 8.0.2
  - refreshenv
  # See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491
  # NB: Do this after refreshenv, otherwise it will be clobbered!
  - set PATH=%APPDATA%\cabal\bin;C:\Program Files\Git\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - cabal --version
  - cabal %CABOPTS% update
  - cabal %CABOPTS% install happy alex

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR"
    # This is just for debugging.
    APPVEYOR_RDP_PASSWORD: "haskell/cabal#5351"

init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - dist-newstyle

build_script:
  - cabal %CABOPTS% new-configure --enable-tests
  - appveyor-retry cabal new-build lib:Cabal --only-dependencies
  - cabal %CABOPTS% new-build lib:Cabal
  - appveyor-retry cabal new-build Cabal:tests --only-dependencies
  # Temporary hack: there's something hanging in thes unit tests, so do them first
  - cabal %CABOPTS% new-run cabal-install:unit-tests
  - cabal %CABOPTS% new-test Cabal
  - appveyor-retry cabal new-build exe:cabal exe:cabal-tests --only-dependencies
  - cabal %CABOPTS% new-build exe:cabal
  - cabal %CABOPTS% new-run cabal-tests -- -j3 --with-cabal=dist-newstyle\build\x86_64-windows\ghc-8.0.2\cabal-install-2.3.0.0\build\cabal\cabal.exe
  - appveyor-retry cabal new-build cabal-install:tests --only-dependencies
  - cabal %CABOPTS% new-test cabal-install
